.github/workflows/ci_checker_on_main_push.yml, .github/workflows/pr_checker.yml, .gitignore, .gitmodules, README.md, build.gradle, checkstyle/naver-checkstyle-rules.xml, checkstyle/naver-checkstyle-suppressions.xml
- Closes #2
1. 시크릿키에 TRAVALUE_APPLICATION, SLACK_WEBHOOK_URL 등록 (application 파일은 empty 상태)
2. pr_checker.yml 구현
3. build.gradle에 checkstyle하는 코드 추가
4. gitignor에 macOS 관련 내용 추가
- application.yml 파일은 아직 구현되지 않아 빈파일로 두었습니다. 추후 구현 시 수정해서 사용할 예정입니다!
=> #2 [feat] CI 구현

README.md
기술 아이콘 추가 및 활동 로그 추가
- Closes #
1. 
-
=> [docs] README에 기술 아이콘과 활동 기록 추가

.gitignore, build.gradle, src/main/java/com/universe/uni/config/SecurityConfig.java, src/main/java/com/universe/uni/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/universe/uni/config/jwt/JwtExceptionFilter.java, src/main/java/com/universe/uni/config/jwt/JwtManager.java, src/main/java/com/universe/uni/service/JwtManager.java
- Closes #13
1. Jwt 관리 클래스 구현
2. Jwt 검증 필터 구현 및 등록
3. SecurityConfig 구현
- 토큰 검증에 대한 에러처리는 오늘 코어타임에 심도있는 고민과 함께 해볼 예정입니다.
- SecurityConfig에서 어떤 url을 [permitAll] or [authenticated] 할지는 추후 변경...
=> #13 [feat] Spring Security Setting with Jwt

.github/workflows/pr_checker.yml
테스트 코드 작성하는 김에 테스트 결과나 보여줘라~
- Closes #
1. 
-
=> feat: Update pr_checker.yml

.github/workflows/cd_on_main.yml, appspec.yml
=> chore: deploy

src/main/java/com/universe/uni/controller/WishCouponController.java, src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java, src/main/java/com/universe/uni/service/WishCouponService.java
=> #27 [feat] 소원권 상세보기 Api 구현

build.gradle, src/main/java/com/universe/uni/config/AuthConfig.java, src/main/java/com/universe/uni/config/FeignConfig.java, src/main/java/com/universe/uni/controller/AuthController.java, src/main/java/com/universe/uni/dto/AuthTokenDto.java, src/main/java/com/universe/uni/external/GoogleApiClient.java, src/main/java/com/universe/uni/external/GoogleAuthClient.java, src/main/java/com/universe/uni/external/KakaoApiClient.java, src/main/java/com/universe/uni/external/KakaoAuthClient.java, src/main/java/com/universe/uni/external/request/GoogleAuthRequest.java, src/main/java/com/universe/uni/external/request/KakaoAuthRequest.java, src/main/java/com/universe/uni/external/response/GoogleAccessTokenResponse.java, src/main/java/com/universe/uni/external/response/GoogleUserInfoResponse.java, src/main/java/com/universe/uni/external/response/KakaoAuthResponse.java, src/main/java/com/universe/uni/external/response/KakaoUserResponse.java, src/main/java/com/universe/uni/repository/GoogleRepository.java, src/main/java/com/universe/uni/repository/KakaoRepository.java, src/main/java/com/universe/uni/repository/RemoteGoogleRepository.java, src/main/java/com/universe/uni/repository/RemoteKakaoRepository.java, src/main/java/com/universe/uni/repository/UserRepository.java, src/main/java/com/universe/uni/service/AuthService.java, src/main/java/com/universe/uni/service/AuthServiceContract.java, src/main/java/com/universe/uni/service/JwtManager.java
=> feat: Kakao Auth

src/main/java/com/universe/uni/controller/MissionController.java, src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java, src/main/java/com/universe/uni/dto/response/MissionContentResponseDto.java, src/main/java/com/universe/uni/repository/MissionContentRepository.java, src/main/java/com/universe/uni/service/MissionService.java
=> #32 [feat] 미션 카테고리 상세 조회하기 Api 구현

src/main/java/com/universe/uni/controller/WishCouponController.java, src/main/java/com/universe/uni/dto/response/WishCouponDto.java, src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java, src/main/java/com/universe/uni/service/WishCouponService.java
=> #39 [feat] 소원권 관련 Api Response 수정

src/main/java/com/universe/uni/controller/UserController.java, src/main/java/com/universe/uni/controller/WishCouponController.java, src/main/java/com/universe/uni/dto/response/UserWishCouponResponseDto.java, src/main/java/com/universe/uni/repository/UserRepository.java, src/main/java/com/universe/uni/repository/WishCouponRepository.java, src/main/java/com/universe/uni/service/UserService.java
=> #29 [feat] 유저 소원권 전체 조회하기 Api 구현

src/main/java/com/universe/uni/controller/CoupleController.java, src/main/java/com/universe/uni/domain/InviteCodeStrategy.java, src/main/java/com/universe/uni/domain/RandomInviteCodeGenerator.java, src/main/java/com/universe/uni/domain/entity/Couple.java, src/main/java/com/universe/uni/dto/request/CreateCoupleRequestDto.java, src/main/java/com/universe/uni/dto/request/JoinCoupleRequestDto.java, src/main/java/com/universe/uni/exception/dto/ErrorType.java, src/main/java/com/universe/uni/repository/CoupleRepository.java, src/main/java/com/universe/uni/service/CoupleService.java, src/main/java/com/universe/uni/service/CoupleServiceContract.java
- Closes #
1. 커플 생성 기능 작성 
2. 커플 연결 기능 작성
-
=> feat: 커플 생성 및 연결 기능 작성

scripts/switch.sh
=> chore: fix switch server port script

src/main/java/com/universe/uni/domain/entity/MissionCategory.java, src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java, src/main/java/com/universe/uni/service/MissionService.java
=> [feat] 미션 카테고리 관련 response에 rule 추가

src/main/java/com/universe/uni/repository/GameRepository.java, src/main/java/com/universe/uni/service/HomeService.java
=> [feat] Game 레포지토리 Jpa 쿼리 수정 (영주 인간 지능 이슈)

src/main/java/com/universe/uni/controller/ShortGameController.java, src/main/java/com/universe/uni/domain/entity/RoundGame.java, src/main/java/com/universe/uni/domain/entity/RoundMission.java, src/main/java/com/universe/uni/domain/entity/WishCoupon.java, src/main/java/com/universe/uni/service/GameService.java
- Closes #59
1. 승부 중단하기 api 구현
-
=> [feat] 승부 중단하기 API

src/main/java/com/universe/uni/controller/HistoryController.java, src/main/java/com/universe/uni/dto/MissionResultDto.java, src/main/java/com/universe/uni/dto/response/GameHistoryResponseDto.java, src/main/java/com/universe/uni/exception/dto/ErrorType.java, src/main/java/com/universe/uni/repository/RoundMissionRepository.java, src/main/java/com/universe/uni/repository/UserGameHistoryRepository.java, src/main/java/com/universe/uni/service/HistoryService.java
=> [feat] 승부 히스토리 전체 조회하기 api 구현

build.gradle, src/main/java/com/universe/uni/config/SwaggerConfig.java, src/main/java/com/universe/uni/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/universe/uni/controller/AuthController.java, src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
=> chore: Add swagger

src/main/java/com/universe/uni/controller/AuthController.java, src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java, src/main/java/com/universe/uni/dto/request/AuthRequestDto.java
=> fix: Fix google and kakao auth redirect path

src/main/java/com/universe/uni/dto/response/CreateShortGameResponseDto.java, src/main/java/com/universe/uni/service/GameService.java
- Closes #69 
1. 승부 생성 시 roundGameId정보도 추가로 보내주는 걸로 수정
-
=> [feat] 승부 생성하기 api 수정

src/main/java/com/universe/uni/repository/GameRepository.java, src/main/java/com/universe/uni/service/HistoryService.java, src/main/java/com/universe/uni/service/HomeService.java
=> [feat] 홈/히스토리 Api userId 로직 및 Game 비어있을 때 null처리 수정

src/main/java/com/universe/uni/controller/WishCouponController.java
=> [feat] HttpStatus No Content일 경우 204로 내려주기

src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java
=> chore: Add Sentry captureException

src/main/java/com/universe/uni/controller/ShortGameController.java, src/main/java/com/universe/uni/service/HistoryService.java
=> [feat] 히스토리 전체조회하기 Api response 안 내려오는 것 수정

src/main/java/com/universe/uni/dto/response/GameHistoryResponseDto.java, src/main/java/com/universe/uni/repository/UserRepository.java, src/main/java/com/universe/uni/service/HistoryService.java
=> [feat] 히스토리 전체 조회하기 Api response에 winner 필드 추가

scripts/run_new.sh, src/main/java/com/universe/uni/controller/AuthController.java, src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java
=> fix: Fix Login logic

appspec.yml, scripts/run_new.sh
=> feat: Update cd script

src/main/java/com/universe/uni/service/AuthService.java, src/main/java/com/universe/uni/service/AuthServiceContract.java
=> fix: Fix SNS Auth Method

src/main/java/com/universe/uni/dto/MissionResultDto.java, src/main/java/com/universe/uni/service/HistoryService.java
=> [feat] 히스토리 response에 content 필드 추가 및 날짜/시간 포멧 수정

appspec.yml, scripts/profile.sh, scripts/start.sh, scripts/stop.sh, scripts/switch.sh
=> chore: Troubleshooting aws script quiescing

src/main/java/com/universe/uni/controller/WishCouponController.java, src/main/java/com/universe/uni/repository/WishCouponRepository.java, src/main/java/com/universe/uni/service/WishCouponService.java
=> [feat] 소원권 받아오는 JPA 수정

build.gradle, src/main/java/com/universe/uni/dto/response/HomeResponseDto.java, src/main/java/com/universe/uni/repository/UserRepository.java, src/main/java/com/universe/uni/service/HomeService.java
=> [feat] 홈 response에 커플의 userId 내려주기

src/main/java/com/universe/uni/controller/UserController.java, src/main/java/com/universe/uni/dto/response/ProfileResponseDto.java, src/main/java/com/universe/uni/service/UserService.java, src/main/java/com/universe/uni/service/UserServiceContract.java
=> [feat] 마이페이지 Api 구현

src/main/java/com/universe/uni/service/GameService.java, src/main/java/com/universe/uni/service/WhitespaceNormalizer.java, src/main/java/com/universe/uni/service/WishCouponService.java
=> [feat] 소원권 입력 공백 처리

src/main/java/com/universe/uni/controller/UserController.java, src/main/java/com/universe/uni/dto/request/UpdateUserProfileRequestDto.java
- Closes #92
1. 유저 프로필 api에서 데이터를 requestParam이 아닌 requestBody로 받아오도록 수정
-
=> [feat] Update Profile API 수정

src/main/java/com/universe/uni/controller/CoupleController.java, src/main/java/com/universe/uni/dto/response/CoupleConnectionResponseDto.java, src/main/java/com/universe/uni/service/CoupleService.java, src/main/java/com/universe/uni/service/CoupleServiceContract.java
- Closes #94
1. 상대 연결 확인하기 API
-
=> feat: 상대 연결 확인하기 API

src/main/java/com/universe/uni/service/HistoryService.java, src/main/java/com/universe/uni/service/UserService.java
=> [feat] 유저소원권조회 / 히스토리 response 정렬 수정

src/main/java/com/universe/uni/service/UserService.java
=> fix: Fix newWishCoupon logic

src/main/java/com/universe/uni/service/WishCouponService.java
- Closes #105
1. 소원권 생성 시 이미지 랜덤 지정
-
=> feat: Add random image to wish coupon

scripts/health_check.sh, scripts/start.sh, scripts/stop.sh, src/main/java/com/universe/uni/config/AuthConfig.java, src/main/java/com/universe/uni/controller/ControllerExceptionAdvice.java, src/main/java/com/universe/uni/controller/CoupleController.java, src/main/java/com/universe/uni/controller/UserController.java, src/main/java/com/universe/uni/external/KakaoApiClient.java, src/main/java/com/universe/uni/external/request/KakaoUnlinkRequest.java, src/main/java/com/universe/uni/external/response/KakaoUnlinkResponse.java, src/main/java/com/universe/uni/repository/KakaoRepository.java, src/main/java/com/universe/uni/repository/RemoteKakaoRepository.java, src/main/java/com/universe/uni/service/AuthService.java, src/main/java/com/universe/uni/service/AuthServiceContract.java, src/main/java/com/universe/uni/service/CoupleService.java, src/main/java/com/universe/uni/service/CoupleServiceContract.java, src/main/java/com/universe/uni/service/UserService.java, src/main/java/com/universe/uni/service/UserServiceContract.java
=> feat: Add delete user

scripts/health_check.sh, scripts/start.sh, scripts/stop.sh
=> fix: Changing a Nondisruptive Deployment Script

src/main/java/com/universe/uni/service/GameService.java
- Closes #111 
기본적으로 게임 생성 부 관련하여 전체적인 함수 분리를 진행하였습니다.
해당 부분 문제가 없다 생각된다면 담당자가 머지 후 작업 들어가 주세요!
@jiyeoon00 
- @jiyeoon00 기존 로직에 대해 수정 시 발생한 문제가 없는지 체크해주세요..! 동작은 동일하게 되도록 코드 수정을 따로 하진 않았으나 발생할 문제가 보인다면 이야기 해주세요 :)
=> feat(111): Separate game creation function

src/main/java/com/universe/uni/domain/MissionTool.java, src/main/java/com/universe/uni/domain/entity/MissionCategory.java, src/main/java/com/universe/uni/domain/entity/convertor/MissionToolAttributeConverter.java
- ref #110 
미션 카테고리에서 필요한 컬럼에 대해 수정하였습니다.
-
=> feat(110): mission category attribute change

src/main/java/com/universe/uni/controller/AuthController.java, src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java, src/main/java/com/universe/uni/dto/AuthTokenDto.java, src/main/java/com/universe/uni/dto/request/AuthRequestDto.java, src/main/java/com/universe/uni/exception/dto/ErrorResponse.java
- Ref #109 
인증 관련 Controller에 사용된 api, dto 에 대해 문서화 진행하였습니다
-
=> [Dosc] AuthController 관련 Docs 추가

src/main/java/com/universe/uni/service/WishCouponService.java
- Closes #123
1. 소원권 상세보기 response 내 닉네임으로 보내주는 오류 수정
- 좋은 하루 보내세요
=> [Fix] 소원권 상세보기 response nickname 수정

.github/workflows/ci_checker_on_main_push.yml, src/main/java/com/universe/uni/domain/entity/MissionContent.java, src/main/java/com/universe/uni/dto/MissionContentDto.java, src/main/java/com/universe/uni/dto/response/RoundMissionContentDto.java, src/main/java/com/universe/uni/service/MissionService.java
- Closes #121 
1. 미션 컨탠츠에 각 미션마다 추천하는 시간을 보여주기 위한 추천시간을 추가했습니다.
- 담당자 기억이 안나서 해당 부분 사용된 MissionContent 관련 내용에 추가가 필요한 부분은 comment 주세요!
=> [Feat] mission content recommend time

src/main/java/com/universe/uni/controller/CoupleController.java, src/main/java/com/universe/uni/controller/docs/AuthControllerContract.java, src/main/java/com/universe/uni/controller/docs/CoupleControllerContract.java, src/main/java/com/universe/uni/dto/request/CreateCoupleRequestDto.java, src/main/java/com/universe/uni/dto/request/JoinCoupleRequestDto.java, src/main/java/com/universe/uni/dto/response/CoupleConnectionResponseDto.java
=> docs: 109 couple controller

src/main/java/com/universe/uni/config/SwaggerConfig.java, src/main/java/com/universe/uni/domain/entity/MissionCategory.java, src/main/java/com/universe/uni/service/GameService.java
- Closes #129 
1. 유저가 선택한 미션 카테고리가 같은 미션을 받는 경우 같은 미션을 커플인 두 유저에게 할당한다.
2. 유저가 선택한 미션 카테고리가 다른 미션을 받는 경우 다른 미션을 커플인 두 유저에게 할당한다.
-
=> [Feat] 유저의 미션은 미션 카테고리에 따라 서로 다르거나 같은 미션을 제공한다.

build.gradle, src/main/java/com/universe/uni/controller/CoupleController.java, src/main/java/com/universe/uni/controller/HistoryController.java, src/main/java/com/universe/uni/controller/MissionController.java, src/main/java/com/universe/uni/controller/ShortGameController.java, src/main/java/com/universe/uni/controller/WishCouponController.java, src/main/java/com/universe/uni/controller/docs/CoupleControllerContract.java, src/main/java/com/universe/uni/controller/docs/HistoryControllerContract.java, src/main/java/com/universe/uni/controller/docs/MissionControllerContract.java, src/main/java/com/universe/uni/controller/docs/ShortGameControllerContract.java, src/main/java/com/universe/uni/controller/docs/WishCouponControllerContract.java, src/main/java/com/universe/uni/dto/MissionResultDto.java, src/main/java/com/universe/uni/dto/RoundMissionDto.java, src/main/java/com/universe/uni/dto/ShortGameDto.java, src/main/java/com/universe/uni/dto/WishCouponDto.java, src/main/java/com/universe/uni/dto/request/CreateShortGameRequestDto.java, src/main/java/com/universe/uni/dto/request/EnterGameResultDto.java, src/main/java/com/universe/uni/dto/request/UpdateWishCouponRequestDto.java, src/main/java/com/universe/uni/dto/response/CoupleDto.java, src/main/java/com/universe/uni/dto/response/CreateShortGameResponseDto.java, src/main/java/com/universe/uni/dto/response/GameHistoryResponseDto.java, src/main/java/com/universe/uni/dto/response/GameReportResponseDto.java, src/main/java/com/universe/uni/dto/response/MissionCategoryDto.java, src/main/java/com/universe/uni/dto/response/MissionCategoryResponseDto.java, src/main/java/com/universe/uni/dto/response/RoundMissionContentDto.java, src/main/java/com/universe/uni/dto/response/WishCouponResponseDto.java
=> docs: swagger docs

src/main/java/com/universe/uni/controller/UserController.java
=> [Feat] Add unlink Sns method

.github/delete-merged-branch-config.yml
=> chore: Create delete-merged-branch-config.yml
